name = "MLJText"
uuid = "5e27fcf9-6bac-46ba-8580-b5712f3d6387"
authors = ["Chris Alexander, Anthony D. Blaom <anthony.blaom@gmail.com>"]
version = "0.1.0"

[deps]
MLJModelInterface = "e80e1ace-859a-464e-9ed9-23947d8ae3ea"
ScientificTypesBase = "30f210dd-8aff-4c5f-94ba-8e64358c1161"
TextAnalysis = "a2db99b7-8b79-58f8-94bf-bbc811eef33d"

[compat]
MLJModelInterface = "1.1.1"
ScientificTypesBase = "1, 2"
TextAnalysis = "0.7.3"
julia = "1.3"

[extras]
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
MLJBase = "a7f614a8-145f-11e9-1d2a-a57a1082229d"
StableRNGs = "860ef19b-820b-49d6-a774-d7a799459cd3"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Distributions", "MLJBase", "StableRNGs", "Test"]
